/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.hash.Hashing;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;

/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 *
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 *
 */
public class App {
    public static void main(String... args) {
      Scanner s = new Scanner(System.in);
      System.out.println("Введите строку: ");
      String str = s.nextLine();
      System.out.println("HashCode введенной строки: "+ Hashing.sha256().hashString(str, StandardCharsets.UTF_8));
    }
}
